import axios from 'axios';

export async function register(params: AuthParams) {
  const response = await axios.post<AuthResult>(
    'http://localhost:4000/api/auth/register',
    params,
  );

  const cookieHeader = response.headers['set-cookie'];

  if (!cookieHeader) {
    throw new Error('No cookie header');
  }

  const result = response.data;

  return {
    result,
    cookieHeader,
  };
}

// Generated by https://quicktype.io

interface AuthParams {
  username: string;
  password: string;
}

export interface AuthResult {
  tokens: Tokens;
  user: User;
}

export interface Tokens {
  accessToken: string;
  refreshToken: string;
}

export interface User {
  id: string;
  username: string;
}
