import { client } from '../client';

export async function createItem(params: CreateItemParams) {
  const response = await client.post<Item>('/api/items', params);
  const result = response.data;
  return result;
}

interface CreateItemParams {
  title: string;
  body: string;
  link: string;
  tags?: string[];
}

// Generated by https://quicktype.io

export interface Item {
  id: number;
  title: string;
  body: string;
  link: string;
  thumbnail: string | null;
  createdAt: Date;
  updatedAt: Date;
  user: User;
}

export interface User {
  id: string;
  username: string;
}
