// Generated by https://quicktype.io

export interface GetItemsResult {
  list: Item[];
  totalCount: number;
  pageInfo: PageInfo;
}

export interface Item {
  id: number;
  title: string;
  body: string;
  link: string;
  thumbnail: string;
  createdAt: string;
  updatedAt: string;
  author: string;
  user: User;
  publisher: Publisher;
  ItemStats: ItemStats;
}

export interface ItemStats {
  id: number;
  likes: number;
  isLiked: boolean;
}

export interface Publisher {
  id: number;
  name: string;
  domain: string;
  favicon: string | null;
}

export interface User {
  id: string;
  username: string;
}

export interface PageInfo {
  hasNextPage: boolean;
  endCursor: number | null;
}

export interface LikeItemResult {
  id: number;
  ItemStats: ItemStats;
}

export type UnlikeItemRoute = LikeItemResult;
