// Generated by https://quicktype.io

export interface GetItemsResult {
  list: Item[];
  totalCount: number;
  pageInfo: PageInfo;
}

export interface Item {
  id: number;
  title: string;
  body: string;
  link: string;
  thumbnail: string;
  createdAt: Date;
  updatedAt: Date;
  author: string;
  user: User;
  publisher: Publisher;
}

export interface Publisher {
  id: number;
  name: string;
  domain: string;
  favicon: string;
}

export interface User {
  id: string;
  username: string;
}

export interface PageInfo {
  hasNextPage: boolean;
  endCursor: number;
}
