version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432'
